version: 0.1
env:
    secrets-manager:
      TOKEN: firstSecret:tokenForSonar
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=devopslabs0 -Dsonar.organization=devopslabs0 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$TOKEN 
